openapi: 3.0.2

info:
  title: Generic blockchain node REST API
  description: Jörmungandr Rest API v1
  version: 0.0.1
  contact:
    url: ''

paths:
  /api/v0/fragments:
    post:
      description: Post a batch of signed transactions
      operationId: PostFragments
      requestBody:
        description: An array of hex-encoded signed transactions
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                pattern: '[0-9a-f]+'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                description: A list of fragment IDs (same order as in input)
                type: array
                items:
                  type: string
                  pattern: '[0-9a-f]+'
              example: ["68dcc12fe0dfe5e7b66ca6f8c959f9aa43b273e120a77fc3e4e2f04f1ecd7968"]
        '400':
          description: One of messages is malformed

  /api/v1/fragments/statuses:
    post:
      description: Get statuses of fragments
      operationId: FragmentStatuses
      requestBody:
        description: List of fragment IDs
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                pattern: '[0-9a-f]+'
            example: ["68dcc12fe0dfe5e7b66ca6f8c959f9aa43b273e120a77fc3e4e2f04f1ecd7968"]
          
      responses:
        '200':
          description: Success. If a fragment is missing from in-memory fragment logs it will not show up in the result dictionary.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  oneOf:
                    - description: Fragment is yet to be processed
                      type: string
                      enum:
                        - Pending
                    - description: "Fragment was rejected and won't be added to a block"
                      type: object
                      required:
                        - Rejected
                      properties:
                        Rejected:
                          type: object
                          required:
                            - reason
                          properties:
                            reason:
                              description: Reason for rejection
                              type: string
                    - description: Fragment was added to a block
                      type: object
                      required:
                        - InABlock
                      properties:
                        InABlock:
                          type: object
                          required:
                            - date
                            - block
                          properties:
                            date:
                              description: Epoch and slot ID of block containing fragment separated with a dot
                              type: string
                              pattern: "[0-9]+\\.[0-9]+"
                            block:
                              description: Block hash where the fragment was last seen
                              type: string
                              pattern: '[0-9a-fa-f]+'
              example: {"68dcc12fe0dfe5e7b66ca6f8c959f9aa43b273e120a77fc3e4e2f04f1ecd7968": "Pending"}
  /api/v0/fragments/logs:
    get:
      description: Gets logs from node message pool
      operationId: FragmentLogs
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - fragment_id
                    - received_from
                    - received_at
                    - last_updated_at
                    - status
                  properties:
                    fragment_id:
                      description: Hex-encoded fragment ID
                      type: string
                      pattern: '[0-9a-f]+'
                    received_from:
                      description: Source of the fragment
                      type: string
                      enum:
                        - Network
                        - Rest
                    received_at:
                      description: When fragment was received by node
                      type: string
                      format: date-time
                    last_updated_at:
                      description: When fragment changed status last time
                      type: string
                      format: date-time
                    status:
                      description: Status of the fragment
                      oneOf:
                        - description: Fragment is yet to be processed
                          type: string
                          enum:
                            - Pending
                        - description: "Fragment was rejected and won't be added to a block"
                          type: object
                          required:
                            - Rejected
                          properties:
                            Rejected:
                              type: object
                              required:
                                - reason
                              properties:
                                reason:
                                  description: Reason for rejection
                                  type: string
                        - description: Fragment was added to a block
                          type: object
                          required:
                            - InABlock
                          properties:
                            InABlock:
                              type: object
                              required:
                                - date
                                - block
                              properties:
                                date:
                                  description: Epoch and slot ID of block containing fragment separated with a dot
                                  type: string
                                  pattern: "[0-9]+\\.[0-9]+"
                                block:
                                  description: Block hash where the fragment was last seen
                                  type: string
                                  pattern: '[0-9a-fA-F]+'
              examples:
                Pending:
                  value:
                    [
                      {
                        "fragment_id": "a50a80e0ce6cb8e19d4381dc2a521c1d3ab8a532029131e440548625b2a4d3e8",
                        "received_from": "Rest",
                        "received_at": "2019-08-12T11:20:52.316544007+00:00",
                        "last_updated_at": "2019-08-12T11:20:52.316544079+00:00",
                        "status": "Pending"
                      }
                    ]
                Rejected:
                  value:
                    [
                      {
                        "fragment_id": "68b36b0e244ff571d4d01026c149a3986bbd7d7deaabac5e3b994171d9c50856",
                        "received_from": "Rest",
                        "received_at": "2019-08-12T11:20:57.758070884+00:00",
                        "last_updated_at": "2019-08-12T11:20:58.005548031+00:00",
                        "status": {
                          "Rejected": {
                            "reason": "The UTxO value (99) in the transaction does not match the actually state value: 100"
                          }
                        }
                      }
                    ]
                InABlock:
                  value:
                    [
                      {
                        "fragment_id": "99e8fbb961e9956cab03779e427b9aad249ddcb4ad7c508f3a80f44091485f01",
                        "received_from": "Rest",
                        "received_at": "2019-08-12T11:21:11.314829989+00:00",
                        "last_updated_at": "2019-08-12T11:21:12.017821060+00:00",
                        "status": {
                          "InABlock": {
                            "date": "114237.32",
                            "block": "d9040ca57e513a36ecd3bb54207dfcd10682200929cad6ada46b521417964174",
                          }
                        }
                      }
                    ]